-- 프리셋 테이블 삭제 (FK 때문에)
DROP TABLE IF EXISTS PRESET_PROCEDURE;
DROP TABLE IF EXISTS PRESET_TABLE;
DROP TABLE IF EXISTS PRESET;

CREATE TABLE PRESET
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(200) NOT NULL UNIQUE,
    description TEXT,
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE PRESET_TABLE
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    preset_id       BIGINT       NOT NULL,
    schema_name     VARCHAR(100) NOT NULL DEFAULT 'public',
    table_name      VARCHAR(200) NOT NULL,
    where_condition TEXT,
    order_num       INT          NOT NULL DEFAULT 0,
    CONSTRAINT fk_pt_preset FOREIGN KEY (preset_id) REFERENCES PRESET (id) ON DELETE CASCADE,
    CONSTRAINT uq_pt UNIQUE (preset_id, schema_name, table_name)
);

-- ============================================================
-- 스키마 카탈로그 테이블 (FK 제약 없음, 재기동 시 유지)
-- ============================================================
CREATE TABLE IF NOT EXISTS SCHEMA_CATALOG
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    schema_name   VARCHAR(100) NOT NULL,
    db_host       VARCHAR(255) NOT NULL,
    db_name       VARCHAR(100) NOT NULL,
    analyzed_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    table_count   INT          NOT NULL DEFAULT 0,
    routine_count INT          NOT NULL DEFAULT 0,
    CONSTRAINT uq_catalog UNIQUE (schema_name, db_host, db_name)
);

CREATE TABLE IF NOT EXISTS CATALOG_TABLE
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    catalog_id  BIGINT       NOT NULL,
    schema_name VARCHAR(100) NOT NULL,
    table_name  VARCHAR(200) NOT NULL,
    CONSTRAINT uq_ct UNIQUE (catalog_id, schema_name, table_name)
);

CREATE TABLE IF NOT EXISTS CATALOG_COLUMN
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    catalog_table_id  BIGINT       NOT NULL,
    catalog_id        BIGINT       NOT NULL,
    schema_name       VARCHAR(100) NOT NULL,
    table_name        VARCHAR(200) NOT NULL,
    column_name       VARCHAR(200) NOT NULL,
    column_name_lower VARCHAR(200) NOT NULL,
    data_type         VARCHAR(100),
    ordinal_position  INT          NOT NULL DEFAULT 0,
    is_nullable       BOOLEAN      NOT NULL DEFAULT TRUE,
    is_pk             BOOLEAN      NOT NULL DEFAULT FALSE,
    column_comment    VARCHAR(500)
);

CREATE TABLE IF NOT EXISTS CATALOG_ROUTINE
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    catalog_id   BIGINT       NOT NULL,
    schema_name  VARCHAR(100) NOT NULL,
    routine_name VARCHAR(200) NOT NULL,
    routine_type VARCHAR(20)  NOT NULL DEFAULT 'FUNCTION',
    ddl_body     CLOB         NOT NULL
);

ALTER TABLE CATALOG_TABLE ADD COLUMN IF NOT EXISTS table_comment VARCHAR(500);

CREATE INDEX IF NOT EXISTS idx_ct_catalog_id    ON CATALOG_TABLE   (catalog_id);
CREATE INDEX IF NOT EXISTS idx_ct_table_name    ON CATALOG_TABLE   (catalog_id, table_name);
CREATE INDEX IF NOT EXISTS idx_cc_catalog_lower ON CATALOG_COLUMN  (catalog_id, column_name_lower);
CREATE INDEX IF NOT EXISTS idx_cc_table_id      ON CATALOG_COLUMN  (catalog_table_id);
CREATE INDEX IF NOT EXISTS idx_cr_catalog_id    ON CATALOG_ROUTINE (catalog_id);
CREATE INDEX IF NOT EXISTS idx_cr_catalog_name  ON CATALOG_ROUTINE (catalog_id, routine_name);
