-- 프로시저 테이블 먼저 삭제 (FK 때문에)
DROP TABLE IF EXISTS PRESET_PROCEDURE;
DROP TABLE IF EXISTS PRESET_TABLE;
DROP TABLE IF EXISTS PRESET;

CREATE TABLE PRESET
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(200) NOT NULL UNIQUE,
    description TEXT,
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE PRESET_TABLE
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    preset_id       BIGINT       NOT NULL,
    schema_name     VARCHAR(100) NOT NULL DEFAULT 'public',
    table_name      VARCHAR(200) NOT NULL,
    where_condition TEXT,
    order_num       INT          NOT NULL DEFAULT 0,
    CONSTRAINT fk_pt_preset FOREIGN KEY (preset_id) REFERENCES PRESET (id) ON DELETE CASCADE,
    CONSTRAINT uq_pt UNIQUE (preset_id, schema_name, table_name)
);
